# services:
#   web:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: pizza_app
#     ports:
#       - "8000:8000"
#     volumes:
#       - .:/app
#     depends_on:
#       - db
#     env_file:
#       - /backend/.env
#   db:
#     image: postgres:15
#     container_name: postgres_pizza_db
#     ports:
#       - "5442:5432"
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: Pizza123
#       POSTGRES_DB: pizza_db
#     volumes:
#       - postgres_data2:/var/lib/postgresql/data

#   frontend:
#     build: 
#       context: ./frontend
#       dockerfile: Dockerfile
#     volumes:
#       - ./frontend:/usr/share/nginx/html
#       # - /usr/share/nginx/html/node_modules
#     ports:
#       - "8080:5173"
# volumes:
#   postgres_data2:


version: "3.8"

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pizza_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - ./backend/.env

  db:
    image: postgres:15
    container_name: postgres_pizza_db
    ports:
      - "5442:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pizza123
      POSTGRES_DB: pizza_db
    volumes:
      - postgres_data2:/var/lib/postgresql/data

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pizza_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "5173:5173"

  nginx:
    image: nginx:latest
    container_name: nginx_pizza_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - frontend

volumes:
  postgres_data2:


# version: '3.8'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - .:/app
#       - /app/node_modules
#     ports:
#       - "5173:5173"
#     environment:
#       - NODE_ENV=development
#     command: npm run dev
