"""Added coupon usage and order relationships

Revision ID: 3a1af75ec0e5
Revises: 84232b2493b4
Create Date: 2025-01-10 07:26:33.159628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a1af75ec0e5'
down_revision: Union[str, None] = '84232b2493b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_coupon_usage', sa.Column('usage_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_coupon_usage', 'usage_limit')
    # ### end Alembic commands ###
