"""Added coupon conflict and order relationships

Revision ID: 637ac11e30dc
Revises: 6cd41b268ad2
Create Date: 2025-01-09 19:41:26.529696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '637ac11e30dc'
down_revision: Union[str, None] = '6cd41b268ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
