"""Fix order coupon relationships

Revision ID: ddeff031f06f
Revises: a3c8ae57f451
Create Date: 2025-01-09 10:13:59.130946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddeff031f06f'
down_revision: Union[str, None] = 'a3c8ae57f451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
