"""Added coupon usage and order relationships

Revision ID: e94e8aa76bde
Revises: 3a1af75ec0e5
Create Date: 2025-01-10 07:45:45.392915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e94e8aa76bde'
down_revision: Union[str, None] = '3a1af75ec0e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('total_price', sa.Float(), nullable=True))
    op.add_column('carts', sa.Column('discounted_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'discounted_price')
    op.drop_column('carts', 'total_price')
    # ### end Alembic commands ###
